name: Actions exercise

on:
  push:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo statement
        run:  echo "Hello world"
      - name: multiline statement
        run: |
          echo "mutiline statement"
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print (platform.processor())
        shell: python